language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - pwd
  - cd webapp
  - ./gradlew war
  - cd build/libs
  - ls -al
  - cd ../../..
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip webapp/build/libs/ROOT.war infrastructure/aws/codedeploy
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al



